{
  "Name": "Citizen",
  "Description": "Be a normal person",
  "Color": "0.06361,0.69302,0.0419,1",
  "Group": "gameplay/jobs/groups/civilian.group",
  "SortingLevel": 0,
  "Models": [
    "models/player/t_side/t_side_player_01/t_side_player_01_v2.vmdl"
  ],
  "Salary": 10,
  "MaxWorkers": 0,
  "Equipment": [
    "gameplay/equipment/weapons/knife/knife.equip"
  ],
  "Vote": false,
  "__references": [],
  "__version": 0
}