{
  "Name": "Chief Cook",
  "Description": "Feed People",
  "Color": "0.91667,0,1,1",
  "Group": "gameplay/jobs/groups/civilian.group",
  "SortingLevel": 0,
  "Models": [
    "models/player/t_side/t_side_player_01/t_side_player_01_v2.vmdl"
  ],
  "Salary": 30,
  "MaxWorkers": 0,
  "Equipment": [
    "gameplay/equipment/default/physgun/physgun.equip",
    "gameplay/equipment/default/hands/hands.equip"
  ],
  "Vote": false,
  "__references": [],
  "__version": 0
}