{
  "Name": "Hobo",
  "Description": "The lowest member of society. Begs for food and money, and builds makeshift homes.",
  "Color": "0.2093,0.08721,0,1",
  "Group": "gameplay/jobs/groups/citizen.group",
  "SortingLevel": 0,
  "Models": [
    "models/player/human/frank_mp.vmdl"
  ],
  "Salary": 0,
  "MaxWorkers": 5,
  "Equipment": [],
  "Vote": false,
  "__references": [
    "sboxmp.frank_mp#58089"
  ],
  "__version": 0
}