{
  "Name": "Mayor",
  "Description": "As the mayor it is your job to keep the city in safe hands and to keep the police force at work.",
  "Color": "0.85581,0.79876,0,1",
  "Group": "gameplay/jobs/groups/government.group",
  "SortingLevel": 0,
  "Models": [
    "models/citizen/citizen.vmdl"
  ],
  "Salary": 90,
  "MaxWorkers": 1,
  "Equipment": [],
  "Vote": true,
  "__references": [],
  "__version": 0
}