{
  "Name": "Mayor",
  "Description": "As the mayor it is your job to keep the city in safe hands and to keep the police force at work.",
  "Color": "0.48627,0.24706,0,1",
  "Group": "gameplay/jobs/groups/goverment.group",
  "SortingLevel": 0,
  "Models": [
    "models/citizen_human/citizen_human_male.vmdl"
  ],
  "Salary": 10,
  "MaxWorkers": 1,
  "Equipment": [],
  "Vote": false,
  "__references": [],
  "__version": 0
}