{
  "Name": "Mercenary",
  "Description": "Mercenary",
  "Color": "0,0.66093,0.94419,1",
  "Group": "gameplay/jobs/groups/illegal.group",
  "SortingLevel": 0,
  "Models": [
    "models/player/t_side/t_side_player_01/t_side_player_01_v2.vmdl"
  ],
  "Salary": 10,
  "MaxWorkers": 4,
  "Equipment": [
    "gameplay/equipment/default/hands/hands.equip",
    "gameplay/equipment/default/physgun/physgun.equip"
  ],
  "Vote": false,
  "__references": [],
  "__version": 0
}