{
  "Name": "Police Officer",
  "Description": "You follow the orders of the chief/mayor and keep peace and order to the community.",
  "Color": "0.19639,0.34374,0.82791,1",
  "Group": "gameplay/jobs/groups/government.group",
  "SortingLevel": 1,
  "Models": [
    "models/player/ct_side/ct_side_player_01/ct_side_player_01_v2.vmdl"
  ],
  "Salary": 70,
  "MaxWorkers": 0,
  "Equipment": [
    "gameplay/equipment/weapons/usp/usp.equip"
  ],
  "Vote": true,
  "__references": [],
  "__version": 0
}